unique-unsorted: unsorted.c unique.c
	gcc -o unique-unsorted unsorted.c unique.c
	
parity-unsorted:  unsorted.c parity.c
	gcc -o parity-unsorted unsorted.c parity.c

unique-sorted: unique.c sorted.c
	gcc -o unique-sorted unique.c sorted.c

parity-sorted: parity.c sorted.c
	gcc -o parity-sorted parity.c sorted.c
